Algoritmo "exercicio3_lista3"

Var
dataNacsi, mesNasci, anoNasci, dataAtual, mesAtual,anoAtual: inteiro

Inicio
Escreval("Informe a data do seu nascimento:")
Leia (dataNacsi)
Escreval("Informe o mês do seu nascimento:")
Leia (mesNasci)
Escreval("Informe o ano do seu nascimento:")
Leia (anoNasci)
Escreval("Informe a data de hoje:")
Leia (dataAtual)
Escreval("Informe o mês de hoje:")
Leia (mesAtual)
Escreval("Informe o ano de hoje:")
Leia (anoAtual)








Fimalgoritmo